//! Export and Cross-Language Interop Generator (`forgen export`)

use std::fs;
use std::path::{Path, PathBuf};

/// Generates a C99/C++ compatible header file (.h) from Datara source
pub fn export_c_header(source_path: &Path, output_header: &Path) -> Result<PathBuf, String> {
    let content = fs::read_to_string(source_path).map_err(|e| {
        format!(
            "Failed to read source file '{}': {}",
            source_path.display(),
            e
        )
    })?;

    let stem = source_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("datara_export");
    let guard = format!("DATARA_{}_H", stem.to_uppercase().replace('-', "_"));

    let mut header = String::new();
    header.push_str("/* Auto-generated by Forgen Export (Datara v1.2) */\n");
    header.push_str(&format!("#ifndef {}\n#define {}\n\n", guard, guard));
    header.push_str("#include <stdint.h>\n#include <stdbool.h>\n#include <stddef.h>\n\n");
    header.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

    header.push_str("#ifndef DATARA_API\n");
    header.push_str("#  if defined(_WIN32) || defined(__CYGWIN__)\n");
    header.push_str("#    define DATARA_API __declspec(dllexport)\n");
    header.push_str("#  else\n");
    header.push_str("#    define DATARA_API __attribute__((visibility(\"default\")))\n");
    header.push_str("#  endif\n");
    header.push_str("#endif\n\n");

    header.push_str("/* Basic Primitive Types */\n");
    header.push_str("typedef int64_t dtr_int;\n");
    header.push_str("typedef double dtr_float;\n");
    header.push_str("typedef const char* dtr_string;\n\n");

    // Extract classes, records, and structs
    let mut in_class = false;
    let mut current_class_name = String::new();
    let mut current_class_fields: Vec<(String, String)> = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();
        let top_kind = crate::lexer::classify_top_level(trimmed);
        let is_agg = top_kind == crate::lexer::TopLevelKind::Class
            || top_kind == crate::lexer::TopLevelKind::Record
            || top_kind == crate::lexer::TopLevelKind::Struct;

        if is_agg {
            let stripped = trimmed.strip_prefix("pub ").unwrap_or(trimmed);
            let name = if let Some(s) = stripped.strip_prefix("class ") {
                s
            } else if let Some(s) = stripped.strip_prefix("record ") {
                s
            } else if let Some(s) = stripped.strip_prefix("struct ") {
                s
            } else {
                stripped
            };
            let name = name
                .split('{')
                .next()
                .unwrap_or("Record")
                .trim()
                .to_string();

            if trimmed.contains('{') && trimmed.ends_with('}') {
                // Single-line aggregate: record Point { x: Float, y: Float }
                if let Some(inner) = trimmed.split('{').nth(1) {
                    let fields_str = inner.trim_end_matches('}').trim();
                    let mut fields = Vec::new();
                    for part in fields_str.split(',') {
                        let part = part.trim();
                        if let Some((fname, ftype)) = part.split_once(':') {
                            fields.push((fname.trim().to_string(), ftype.trim().to_string()));
                        }
                    }
                    header.push_str("typedef struct {\n");
                    for (fname, ftype) in &fields {
                        let c_type = map_datara_type_to_c(ftype);
                        header.push_str(&format!("    {} {};\n", c_type, fname));
                    }
                    header.push_str(&format!("}} {};\n\n", name));
                }
            } else {
                // Multi-line aggregate
                in_class = true;
                current_class_name = name;
                current_class_fields.clear();
            }
        } else if in_class {
            if trimmed == "}" {
                in_class = false;
                header.push_str("typedef struct {\n");
                for (fname, ftype) in &current_class_fields {
                    let c_type = map_datara_type_to_c(ftype);
                    header.push_str(&format!("    {} {};\n", c_type, fname));
                }
                header.push_str(&format!("}} {};\n\n", current_class_name));
            } else if trimmed.contains(':') {
                let parts: Vec<&str> = trimmed.split(':').collect();
                if parts.len() == 2 {
                    let fname = parts[0].trim();
                    let ftype = parts[1].trim().trim_end_matches(',').trim();
                    current_class_fields.push((fname.to_string(), ftype.to_string()));
                }
            }
        } else if top_kind == crate::lexer::TopLevelKind::Fn
            || trimmed.starts_with("fn ")
            || trimmed.starts_with("pub fn ")
        {
            let sig_line = trimmed
                .strip_prefix("pub ")
                .unwrap_or(trimmed)
                .strip_prefix("fn ")
                .unwrap_or("");
            let sig_end = sig_line.find('{').unwrap_or(sig_line.len());
            let sig = &sig_line[..sig_end].trim();

            if let Some(paren_idx) = sig.find('(') {
                let fn_name = sig[..paren_idx].trim();
                let rest = &sig[paren_idx..];
                let ret_type = if let Some(arrow_idx) = rest.find("->") {
                    rest[arrow_idx + 2..].trim()
                } else {
                    "Unit"
                };

                let c_ret = map_datara_type_to_c(ret_type);
                let params_part = rest[..rest.find("->").unwrap_or(rest.len())].trim();
                let c_params = format_c_params(params_part);

                header.push_str(&format!("DATARA_API {} {}{};\n", c_ret, fn_name, c_params));
            }
        }
    }

    header.push_str("\n#ifdef __cplusplus\n}\n#endif\n\n");
    header.push_str(&format!("#endif /* {} */\n", guard));

    if let Some(parent) = output_header.parent() {
        let _ = fs::create_dir_all(parent);
    }
    fs::write(output_header, header).map_err(|e| {
        format!(
            "Failed to write header to '{}': {}",
            output_header.display(),
            e
        )
    })?;

    Ok(output_header.to_path_buf())
}

/// Convert Datara parameter list like `(x: Float, y: Float)` to C signature `(double x, double y)`
fn format_c_params(param_str: &str) -> String {
    let inner = param_str
        .trim()
        .trim_start_matches('(')
        .trim_end_matches(')')
        .trim();
    if inner.is_empty() {
        return "(void)".to_string();
    }
    let mut c_params = Vec::new();
    for part in inner.split(',') {
        let part = part.trim();
        if part.is_empty() {
            continue;
        }
        if let Some((pname, ptype)) = part.split_once(':') {
            let c_type = map_datara_type_to_c(ptype.trim());
            c_params.push(format!("{} {}", c_type, pname.trim()));
        } else {
            c_params.push(part.to_string());
        }
    }
    if c_params.is_empty() {
        "(void)".to_string()
    } else {
        format!("({})", c_params.join(", "))
    }
}

pub fn map_datara_type_to_c(dtr_type: &str) -> String {
    let t = dtr_type.trim();
    match t {
        "Int" | "i64" => "int64_t".to_string(),
        "i32" => "int32_t".to_string(),
        "i16" => "int16_t".to_string(),
        "i8" => "int8_t".to_string(),
        "u64" => "uint64_t".to_string(),
        "u32" => "uint32_t".to_string(),
        "u16" => "uint16_t".to_string(),
        "u8" => "uint8_t".to_string(),
        "Float" | "f64" => "double".to_string(),
        "f32" => "float".to_string(),
        "Str" | "String" => "const char*".to_string(),
        "Bool" | "bool" => "bool".to_string(),
        "Unit" | "void" => "void".to_string(),
        _ => {
            if t.starts_with("List<") || t.starts_with("Array<") {
                "void*".to_string()
            } else {
                t.to_string()
            }
        }
    }
}

/// Generates the standard C embed API header (`datara_embed.h`) exposing
/// the in-process Datara runtime host functions.
pub fn export_embed_header(output_header: &Path) -> Result<PathBuf, String> {
    let header = r#"/* Auto-generated by Forgen (Datara v1.2 Embed Profile) */
#ifndef DATARA_EMBED_H
#define DATARA_EMBED_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef FORGEN_API
#  if defined(_WIN32) || defined(__CYGWIN__)
#    define FORGEN_API __declspec(dllimport)
#  else
#    define FORGEN_API
#  endif
#endif

/**
 * Initialize the Forgen embed runtime.
 * Returns 0 on success, or a negative error code on failure.
 */
FORGEN_API int32_t forgen_init(void);

/**
 * Load and compile a Datara module (.dtr) into process memory via JIT or shared object.
 * Returns 0 on success, or -1 on failure (inspect via forgen_last_error).
 */
FORGEN_API int32_t forgen_load_module(const char* module_path);

/**
 * Call a function exported by the loaded module.
 *
 * @param func_name  Null-terminated function name
 * @param args       Pointer to 64-bit argument array
 * @param arg_count  Number of arguments in args (up to 8)
 * @param out_result Pointer where the 64-bit return value will be stored
 * @return 0 on success, or -1 on failure
 */
FORGEN_API int32_t forgen_call_fn(
    const char* func_name,
    const int64_t* args,
    size_t arg_count,
    int64_t* out_result
);

/**
 * Shuts down the embed runtime, freeing all loaded modules and cached JIT memory.
 * Returns 0 on success.
 */
FORGEN_API int32_t forgen_shutdown(void);

/**
 * Returns the last error message as a null-terminated UTF-8 string.
 * The pointer is thread-local and valid until the next call on this thread.
 */
FORGEN_API const char* forgen_last_error(void);

#ifdef __cplusplus
}
#endif

#endif /* DATARA_EMBED_H */
"#;

    if let Some(parent) = output_header.parent() {
        let _ = fs::create_dir_all(parent);
    }
    fs::write(output_header, header).map_err(|e| {
        format!(
            "Failed to write embed header to '{}': {}",
            output_header.display(),
            e
        )
    })?;

    Ok(output_header.to_path_buf())
}

/// Compiles source into a native shared library (.dll / .so / .dylib)
pub fn export_shared_library(source_path: &Path, output_lib: &Path) -> Result<PathBuf, String> {
    export_shared_library_opt(source_path, output_lib, "3")
}

/// Compiles source into a native shared library with explicit optimization level
pub fn export_shared_library_opt(
    source_path: &Path,
    output_lib: &Path,
    opt_level: &str,
) -> Result<PathBuf, String> {
    if let Some(p) = output_lib.parent() {
        let _ = fs::create_dir_all(p);
    }
    let compiler = crate::driver::ForgenCompiler::new(opt_level).with_llvm(true);
    let res = compiler.compile_file(source_path, Some(output_lib));
    if !res.success {
        return Err(res.error.unwrap_or_else(|| "Compilation failed".into()));
    }
    Ok(output_lib.to_path_buf())
}

/// Exports a complete C embed package consisting of:
/// 1. Native shared library (.dll / .so / .dylib)
/// 2. Module-specific C header (<module>.h)
/// 3. Standard embed runtime C header (datara_embed.h)
pub fn export_embed_package(
    source_path: &Path,
    output_dir: &Path,
    opt_level: &str,
) -> Result<(PathBuf, PathBuf, PathBuf), String> {
    let stem = source_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("datara_export");
    let lib_ext = if cfg!(target_os = "windows") {
        "dll"
    } else if cfg!(target_os = "macos") {
        "dylib"
    } else {
        "so"
    };
    let output_lib = output_dir.join(format!("{}.{}", stem, lib_ext));
    let output_mod_h = output_dir.join(format!("{}.h", stem));
    let output_embed_h = output_dir.join("datara_embed.h");

    export_shared_library_opt(source_path, &output_lib, opt_level)?;
    export_c_header(source_path, &output_mod_h)?;
    export_embed_header(&output_embed_h)?;

    Ok((output_lib, output_mod_h, output_embed_h))
}
