//! Export and Cross-Language Interop Generator (`forgen export`)

use std::fs;
use std::path::{Path, PathBuf};

/// Generates a C99/C++ compatible header file (.h) from Datara source
pub fn export_c_header(source_path: &Path, output_header: &Path) -> Result<PathBuf, String> {
    let content = fs::read_to_string(source_path).map_err(|e| {
        format!(
            "Failed to read source file '{}': {}",
            source_path.display(),
            e
        )
    })?;

    let stem = source_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("datara_export");
    let guard = format!("DATARA_{}_H", stem.to_uppercase().replace('-', "_"));

    let mut header = String::new();
    header.push_str("/* Auto-generated by Forgen Export (Datara v0.1) */\n");
    header.push_str(&format!("#ifndef {}\n#define {}\n\n", guard, guard));
    header.push_str("#include <stdint.h>\n#include <stdbool.h>\n#include <stddef.h>\n\n");
    header.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

    header.push_str("#ifndef DATARA_API\n");
    header.push_str("#  if defined(_WIN32) || defined(__CYGWIN__)\n");
    header.push_str("#    define DATARA_API __declspec(dllexport)\n");
    header.push_str("#  else\n");
    header.push_str("#    define DATARA_API __attribute__((visibility(\"default\")))\n");
    header.push_str("#  endif\n");
    header.push_str("#endif\n\n");

    header.push_str("/* Basic Primitive Types */\n");
    header.push_str("typedef int64_t dtr_int;\n");
    header.push_str("typedef double dtr_float;\n");
    header.push_str("typedef const char* dtr_string;\n\n");

    // Extract classes
    let mut in_class = false;
    let mut current_class_name = String::new();
    let mut current_class_fields: Vec<(String, String)> = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("class ") {
            in_class = true;
            let name = trimmed
                .strip_prefix("class ")
                .and_then(|s| s.split('{').next())
                .unwrap_or("Class")
                .trim()
                .to_string();
            current_class_name = name;
            current_class_fields.clear();
        } else if in_class {
            if trimmed == "}" {
                in_class = false;
                header.push_str("typedef struct {\n");
                for (fname, ftype) in &current_class_fields {
                    let c_type = map_datara_type_to_c(ftype);
                    header.push_str(&format!("    {} {};\n", c_type, fname));
                }
                header.push_str(&format!("}} {};\n\n", current_class_name));
            } else if trimmed.contains(':') {
                let parts: Vec<&str> = trimmed.split(':').collect();
                if parts.len() == 2 {
                    let fname = parts[0].trim();
                    let ftype = parts[1].trim();
                    current_class_fields.push((fname.to_string(), ftype.to_string()));
                }
            }
        } else if trimmed.starts_with("fn ") || trimmed.starts_with("pub fn ") {
            let sig_line = trimmed
                .strip_prefix("pub ")
                .unwrap_or(trimmed)
                .strip_prefix("fn ")
                .unwrap_or("");
            let sig_end = sig_line.find('{').unwrap_or(sig_line.len());
            let sig = &sig_line[..sig_end].trim();

            if let Some(paren_idx) = sig.find('(') {
                let fn_name = sig[..paren_idx].trim();
                let rest = &sig[paren_idx..];
                let ret_type = if let Some(arrow_idx) = rest.find("->") {
                    rest[arrow_idx + 2..].trim()
                } else {
                    "Unit"
                };

                let c_ret = map_datara_type_to_c(ret_type);
                header.push_str(&format!(
                    "DATARA_API {} {}{};\n",
                    c_ret,
                    fn_name,
                    rest[..rest.find("->").unwrap_or(rest.len())].trim()
                ));
            }
        }
    }

    header.push_str("\n#ifdef __cplusplus\n}\n#endif\n\n");
    header.push_str(&format!("#endif /* {} */\n", guard));

    if let Some(parent) = output_header.parent() {
        let _ = fs::create_dir_all(parent);
    }
    fs::write(output_header, header).map_err(|e| {
        format!(
            "Failed to write header to '{}': {}",
            output_header.display(),
            e
        )
    })?;

    Ok(output_header.to_path_buf())
}

fn map_datara_type_to_c(dtr_type: &str) -> &'static str {
    match dtr_type {
        "Int" => "int64_t",
        "Float" => "double",
        "Str" | "String" => "const char*",
        "Bool" => "bool",
        "Unit" => "void",
        _ => "void*",
    }
}

/// Compiles source into a native shared library (.dll / .so / .dylib)
///
/// The former implementation invoked `forgen build --llvm` (which produces an
/// *executable*) and then returned the requested library path — a file that
/// was never created. Compilation now happens in-process: DMIR → LLVM IR →
/// `clang -shared` linked against the Datara runtime.
pub fn export_shared_library(source_path: &Path, output_lib: &Path) -> Result<PathBuf, String> {
    let compiler = crate::driver::ForgenCompiler::new("release").with_llvm(true);
    let res = compiler.compile_file(source_path, None);
    if !res.success {
        return Err(res.error.unwrap_or_else(|| "Compilation failed".into()));
    }
    let llvm_ir = res
        .llvm_source
        .ok_or_else(|| "LLVM IR was not generated for the shared-library export".to_string())?;

    let ll_path = output_lib.with_extension("ll");
    fs::write(&ll_path, llvm_ir)
        .map_err(|e| format!("Failed to write LLVM IR '{}': {}", ll_path.display(), e))?;

    // Locate the Datara runtime: prefer the C source next to the compiler
    // checkout, then the compiled archive (installed layouts).
    let rt_candidates = [
        PathBuf::from(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/src/runtime/datara_runtime.c"
        )),
        crate::runtime::runtime_lib_path(),
    ];
    let rt_path = rt_candidates.into_iter().find(|p| p.exists());

    crate::codegen::linker::compile_shared_with_clang(
        &ll_path,
        rt_path.as_deref(),
        output_lib,
        "3",
    )?;

    Ok(output_lib.to_path_buf())
}
