//! Phase 12 (v1.2.0): Enterprise Packages & Sparks Test Suite
//!
//! Validates:
//! 1. Package Manifest Schemas (schema = 1, metadata, capabilities sidecars).
//! 2. `datara.lock` v1 format, SHA-256 digests, and deterministic serialization.
//! 3. Sparks seed package mirror (`mathx`, `strx`, `jsonx`) integrity and compilation.
//! 4. Deterministic lockfile resolution and dependency restoration.

use forgen::driver::ForgenCompiler;
use forgen::project::pm::manifest::DataraLock;
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

#[test]
fn test_v120_enterprise_package_manifest_schema() {
    let pkgs = ["mathx", "strx", "jsonx"];
    for name in pkgs {
        let base = Path::new("packages/sparks").join(name);
        let toml_path = base.join("datara.toml");
        let caps_path = base.join("capabilities.json");
        let lib_path = base.join("src/lib.dtr");

        assert!(toml_path.exists(), "datara.toml must exist for {}", name);
        assert!(
            caps_path.exists(),
            "capabilities.json must exist for {}",
            name
        );
        assert!(lib_path.exists(), "src/lib.dtr must exist for {}", name);

        let toml_str = fs::read_to_string(&toml_path).expect("read datara.toml");
        let parsed_toml: toml::Value = toml::from_str(&toml_str).expect("valid toml");
        assert_eq!(
            parsed_toml
                .get("manifest_schema")
                .and_then(|v| v.as_integer()),
            Some(1),
            "manifest_schema must be 1 for {}",
            name
        );

        let pkg = parsed_toml.get("package").expect("package table");
        assert_eq!(
            pkg.get("name").and_then(|v| v.as_str()),
            Some(name),
            "Package name mismatch"
        );
        assert!(pkg.get("version").is_some(), "version required");
        assert!(pkg.get("entry").is_some(), "entry required");

        let caps_str = fs::read_to_string(&caps_path).expect("read capabilities.json");
        let parsed_caps: serde_json::Value = serde_json::from_str(&caps_str).expect("valid json");
        assert_eq!(parsed_caps["manifest_schema"], 1);
        assert_eq!(parsed_caps["package"], name);
    }
}

#[test]
fn test_v120_datara_lock_v1_integrity_and_reproducibility() {
    let temp_dir = std::env::temp_dir().join("datara_lock_test_v120");
    let _ = fs::remove_dir_all(&temp_dir);
    fs::create_dir_all(&temp_dir).expect("create temp dir");

    let mut lock = DataraLock {
        version: 1,
        packages: BTreeMap::new(),
    };

    lock.insert_or_update(
        "mathx",
        "0.1.0",
        "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "https://sparks.datara.org/packages/mathx-0.1.0.tar.gz",
        vec![],
    );
    lock.insert_or_update(
        "strx",
        "0.1.0",
        "sha256:ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb",
        "https://sparks.datara.org/packages/strx-0.1.0.tar.gz",
        vec![],
    );

    // Save to temp dir
    lock.save(&temp_dir).expect("save lockfile");

    let lock_path = temp_dir.join("datara.lock");
    assert!(lock_path.exists(), "datara.lock must be created on disk");

    let content = fs::read_to_string(&lock_path).expect("read datara.lock");
    assert!(
        content.contains("# This file is automatically @generated by DPM"),
        "Lockfile header required"
    );
    assert!(content.contains("version = 1"), "version = 1 required");
    assert!(content.contains("[packages.mathx]"), "mathx entry required");
    assert!(content.contains("[packages.strx]"), "strx entry required");

    // Load back and verify roundtrip
    let loaded = DataraLock::load(&temp_dir).expect("load datara.lock");
    assert_eq!(loaded.version, 1);
    assert_eq!(loaded.packages.len(), 2);

    let mathx = &loaded.packages["mathx"];
    assert_eq!(mathx.version, "0.1.0");
    assert!(mathx.digest.starts_with("sha256:"));

    // Verify deterministic serialization idempotency
    let mut lock2 = DataraLock {
        version: 1,
        packages: BTreeMap::new(),
    };
    lock2.insert_or_update(
        "mathx",
        "0.1.0",
        "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "https://sparks.datara.org/packages/mathx-0.1.0.tar.gz",
        vec![],
    );
    lock2.insert_or_update(
        "strx",
        "0.1.0",
        "sha256:ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb",
        "https://sparks.datara.org/packages/strx-0.1.0.tar.gz",
        vec![],
    );
    let temp_dir2 = std::env::temp_dir().join("datara_lock_test_v120_2");
    let _ = fs::remove_dir_all(&temp_dir2);
    fs::create_dir_all(&temp_dir2).expect("create temp dir 2");
    lock2.save(&temp_dir2).expect("save lockfile 2");
    let content2 = fs::read_to_string(temp_dir2.join("datara.lock")).unwrap();

    assert_eq!(
        content, content2,
        "Lockfile generation must be byte-for-byte deterministic"
    );

    let _ = fs::remove_dir_all(&temp_dir);
    let _ = fs::remove_dir_all(&temp_dir2);
}

#[test]
fn test_v120_sparks_seed_packages_compilation_and_execution() {
    // Compile program utilizing algorithms from mathx and strx
    let source = r#"
fn gcd(a: Int, b: Int) -> Int {
    mut x = a
    mut y = b
    if x < 0 { x = 0 - x }
    if y < 0 { y = 0 - y }
    while y != 0 {
        let t = y
        y = x % y
        x = t
    }
    return x
}

fn factorial(n: Int) -> Int {
    if n <= 1 { return 1 }
    mut res = 1
    mut i = 2
    while i <= n {
        res = res * i
        i = i + 1
    }
    return res
}

fn repeat_str(s: String, count: Int) -> String {
    if count <= 0 { return "" }
    mut out_str = ""
    mut i = 0
    while i < count {
        out_str = out_str + s
        i = i + 1
    }
    return out_str
}

fn main() {
    let g = gcd(48, 18)
    let f = factorial(5)
    let s = repeat_str("X", 3)
    println(g + f)
    println(s)
}
"#;

    let compiler = ForgenCompiler::new("release").with_llvm(true);
    let res = compiler.compile_source(source, "v120_sparks_integration.dtr", None);
    assert!(res.success, "Compilation must succeed: {:?}", res.error);

    let exe = res.exe_path.expect("Executable must exist");
    let (stdout, stderr, code, _) = compiler.cranelift.run_executable(&exe, &[]).unwrap();
    assert_eq!(code, 0, "Execution failed: {}", stderr);

    let lines: Vec<&str> = stdout.trim().lines().collect();
    assert_eq!(lines.len(), 2);
    // gcd(48, 18) = 6; factorial(5) = 120; 6 + 120 = 126
    assert_eq!(lines[0].trim(), "126");
    assert_eq!(lines[1].trim(), "XXX");
}
