//! Embedded Datara Standard Library
//! Provides zero-dependency, in-memory fallback for all standard library modules
//! when running in standalone, air-gapped, or globally installed environments.

pub fn get_embedded_stdlib_source(module_path: &str) -> Option<&'static str> {
    match module_path {
        "collections.list" => Some(include_str!("../stdlib/collections/list.dtr")),
        "collections.map" => Some(include_str!("../stdlib/collections/map.dtr")),
        "crypto.hash" => Some(include_str!("../stdlib/crypto/hash.dtr")),
        "database.kv" => Some(include_str!("../stdlib/database/kv.dtr")),
        "database.redis" => Some(include_str!("../stdlib/database/redis.dtr")),
        "database.sql" => Some(include_str!("../stdlib/database/sql.dtr")),
        "http.client" => Some(include_str!("../stdlib/http/client.dtr")),
        "http.server" => Some(include_str!("../stdlib/http/server.dtr")),
        "http.types" => Some(include_str!("../stdlib/http/types.dtr")),
        "interop.python" => Some(include_str!("../stdlib/interop/python.dtr")),
        "interop.rust" => Some(include_str!("../stdlib/interop/rust.dtr")),
        "io.args" => Some(include_str!("../stdlib/io/args.dtr")),
        "io.env" => Some(include_str!("../stdlib/io/env.dtr")),
        "io.fs" => Some(include_str!("../stdlib/io/fs.dtr")),
        "json.parser" => Some(include_str!("../stdlib/json/parser.dtr")),
        "json.serializer" => Some(include_str!("../stdlib/json/serializer.dtr")),
        "json.types" => Some(include_str!("../stdlib/json/types.dtr")),
        "math.math" => Some(include_str!("../stdlib/math/math.dtr")),
        "math" => Some(include_str!("../stdlib/math/math.dtr")),
        "net.socket" => Some(include_str!("../stdlib/net/socket.dtr")),
        "result.option" => Some(include_str!("../stdlib/result/option.dtr")),
        "result.result" => Some(include_str!("../stdlib/result/result.dtr")),
        "sys.process" => Some(include_str!("../stdlib/sys/process.dtr")),
        "text.format" => Some(include_str!("../stdlib/text/format.dtr")),
        "text.string" => Some(include_str!("../stdlib/text/string.dtr")),
        "time.clock" => Some(include_str!("../stdlib/time/clock.dtr")),
        "ui.components" => Some(include_str!("../stdlib/ui/components.dtr")),
        "ui.element" => Some(include_str!("../stdlib/ui/element.dtr")),
        "ui.native" => Some(include_str!("../stdlib/ui/native.dtr")),
        "ui.page" => Some(include_str!("../stdlib/ui/page.dtr")),
        "ui.reactive" => Some(include_str!("../stdlib/ui/reactive.dtr")),
        "ui.styles" => Some(include_str!("../stdlib/ui/styles.dtr")),
        "ai.tensor" => Some(include_str!("../stdlib/ai/tensor.dtr")),
        "embedded.interrupt" => Some(include_str!("../stdlib/embedded/interrupt.dtr")),
        "embedded.mmio" => Some(include_str!("../stdlib/embedded/mmio.dtr")),
        "interop.universal" => Some(include_str!("../stdlib/interop/universal.dtr")),
        "kernel.arch.x86_64.mmu" => Some(include_str!("../stdlib/kernel/mmu.dtr")),
        "kernel.mmu" => Some(include_str!("../stdlib/kernel/mmu.dtr")),
        "kernel.arch.x86_64.ports" => Some(include_str!("../stdlib/kernel/ports.dtr")),
        "kernel.ports" => Some(include_str!("../stdlib/kernel/ports.dtr")),
        "sys.arena" => Some(include_str!("../stdlib/sys/arena.dtr")),
        "web.webgl" => Some(include_str!("../stdlib/web/webgl.dtr")),
        "web.webgpu" => Some(include_str!("../stdlib/web/webgpu.dtr")),
        _ => None,
    }
}

pub const ALL_EMBEDDED_MODULES: &[&str] = &[
    "collections.list",
    "collections.map",
    "crypto.hash",
    "database.kv",
    "database.redis",
    "database.sql",
    "http.client",
    "http.server",
    "http.types",
    "interop.python",
    "interop.rust",
    "io.args",
    "io.env",
    "io.fs",
    "json.parser",
    "json.serializer",
    "json.types",
    "math.math",
    "net.socket",
    "result.option",
    "result.result",
    "sys.process",
    "text.format",
    "text.string",
    "time.clock",
    "ui.components",
    "ui.element",
    "ui.native",
    "ui.page",
    "ui.reactive",
    "ui.styles",
    "ui.web",
    "ai.tensor",
    "embedded.interrupt",
    "embedded.mmio",
    "interop.universal",
    "kernel.arch.x86_64.mmu",
    "kernel.mmu",
    "kernel.arch.x86_64.ports",
    "kernel.ports",
    "sys.arena",
    "web.webgl",
    "web.webgpu",
];
