use super::registry::HyperGridRegistry;
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap};
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SparksPackageManifest {
    pub schema: u32,
    pub name: String,
    pub version: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub author: String,
    #[serde(default)]
    pub license: String,
    pub tarball_url: String,
    pub sha256: String,
    #[serde(default)]
    pub public_key: Option<String>,
    #[serde(default)]
    pub signature: Option<String>,
    #[serde(default)]
    pub capabilities: Vec<String>,
    #[serde(default)]
    pub determinism_receipt: Option<SparksDeterminismReceipt>,
    #[serde(default)]
    pub dependencies: HashMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SparksDeterminismReceipt {
    pub checksum: String,
    pub compiler: String,
    pub target: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackageCapability {
    pub name: String,
    pub description: String,
    pub is_sensitive: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperGridPackage {
    pub name: String,
    pub version: String,
    pub description: String,
    pub author: String,
    pub license: String,
    pub digest: String,
    pub capabilities: Vec<String>,
    pub dependencies: Vec<String>,
    pub entry: String,
    pub files: HashMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct LockedPackage {
    pub version: String,
    pub digest: String,
    pub source: String,
    #[serde(default)]
    pub dependencies: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataraLock {
    pub version: u32,
    #[serde(default)]
    pub packages: BTreeMap<String, LockedPackage>,
}

impl Default for DataraLock {
    fn default() -> Self {
        Self {
            version: 1,
            packages: BTreeMap::new(),
        }
    }
}

impl DataraLock {
    pub fn load(project_root: &Path) -> Option<Self> {
        let lock_path = project_root.join("datara.lock");
        if !lock_path.exists() {
            return None;
        }
        let content = fs::read_to_string(&lock_path).ok()?;
        toml::from_str(&content).ok()
    }

    pub fn save(&self, project_root: &Path) -> Result<(), String> {
        let lock_path = project_root.join("datara.lock");
        let toml_str = toml::to_string_pretty(self)
            .map_err(|e| format!("Failed to serialize datara.lock: {}", e))?;
        let header = "# This file is automatically @generated by DPM (Datara Package Manager).\n# It is recommended to commit this file to version control.\n\n";
        fs::write(&lock_path, format!("{}{}", header, toml_str))
            .map_err(|e| format!("Failed to write datara.lock: {}", e))?;
        Ok(())
    }

    pub fn insert_or_update(
        &mut self,
        name: &str,
        version: &str,
        digest: &str,
        source: &str,
        deps: Vec<String>,
    ) {
        self.packages.insert(
            name.to_string(),
            LockedPackage {
                version: version.to_string(),
                digest: digest.to_string(),
                source: source.to_string(),
                dependencies: deps,
            },
        );
    }

    pub fn remove(&mut self, name: &str) {
        self.packages.remove(name);
    }

    /// Restores all locked dependencies deterministically into the project.
    pub fn restore(
        &self,
        registry: &HyperGridRegistry,
        project_root: &Path,
    ) -> Result<usize, String> {
        let mut restored = 0;
        for (pkg_name, locked) in &self.packages {
            let pkg_dir = project_root.join("packages").join(pkg_name);
            if !pkg_dir.exists() {
                if let Some(pkg) = registry.lookup(pkg_name) {
                    registry.install_with_source(pkg, project_root, &locked.source)?;
                    restored += 1;
                } else if locked.source.starts_with("http://")
                    || locked.source.starts_with("https://")
                    || locked.source.starts_with("file://")
                {
                    registry.fetch_and_install_tarball(
                        pkg_name,
                        &locked.version,
                        &locked.source,
                        &locked.digest,
                        project_root,
                    )?;
                    restored += 1;
                } else {
                    return Err(format!(
                        "Cannot restore locked package '{}': not in registry and has invalid source URL '{}'",
                        pkg_name, locked.source
                    ));
                }
            }
        }
        Ok(restored)
    }
}
