use crate::project::manifest::DataraManifest;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackageCapability {
    pub name: String,
    pub description: String,
    pub is_sensitive: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperGridPackage {
    pub name: String,
    pub version: String,
    pub description: String,
    pub author: String,
    pub license: String,
    pub digest: String,
    pub capabilities: Vec<String>,
    pub dependencies: Vec<String>,
    pub entry: String,
    pub files: HashMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct LockedPackage {
    pub version: String,
    pub digest: String,
    pub source: String,
    #[serde(default)]
    pub dependencies: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataraLock {
    pub version: u32,
    #[serde(default)]
    pub packages: HashMap<String, LockedPackage>,
}

impl Default for DataraLock {
    fn default() -> Self {
        Self {
            version: 1,
            packages: HashMap::new(),
        }
    }
}

impl DataraLock {
    pub fn load(project_root: &Path) -> Option<Self> {
        let lock_path = project_root.join("datara.lock");
        if !lock_path.exists() {
            return None;
        }
        let content = fs::read_to_string(&lock_path).ok()?;
        toml::from_str(&content).ok()
    }

    pub fn save(&self, project_root: &Path) -> Result<(), String> {
        let lock_path = project_root.join("datara.lock");
        let toml_str = toml::to_string_pretty(self)
            .map_err(|e| format!("Failed to serialize datara.lock: {}", e))?;
        let header = "# This file is automatically @generated by DPM (Datara Package Manager).\n# It is recommended to commit this file to version control.\n\n";
        fs::write(&lock_path, format!("{}{}", header, toml_str))
            .map_err(|e| format!("Failed to write datara.lock: {}", e))?;
        Ok(())
    }

    pub fn insert_or_update(
        &mut self,
        name: &str,
        version: &str,
        digest: &str,
        source: &str,
        deps: Vec<String>,
    ) {
        self.packages.insert(
            name.to_string(),
            LockedPackage {
                version: version.to_string(),
                digest: digest.to_string(),
                source: source.to_string(),
                dependencies: deps,
            },
        );
    }

    pub fn remove(&mut self, name: &str) {
        self.packages.remove(name);
    }
}

pub struct HyperGridRegistry {
    pub store_path: PathBuf,
    pub packages: HashMap<String, HyperGridPackage>,
}

impl Default for HyperGridRegistry {
    fn default() -> Self {
        Self::new()
    }
}

impl HyperGridRegistry {
    pub fn new() -> Self {
        let store_path = Self::resolve_store_dir();
        let mut reg = Self {
            store_path,
            packages: HashMap::new(),
        };
        reg.init_curated_index();
        reg
    }

    pub fn resolve_store_dir() -> PathBuf {
        if let Ok(datara_home) = std::env::var("DATARA_HOME") {
            let p = PathBuf::from(datara_home).join("store");
            let _ = fs::create_dir_all(&p);
            return p;
        }

        if let Ok(home) = std::env::var("USERPROFILE").or_else(|_| std::env::var("HOME")) {
            let p = PathBuf::from(home).join(".datara").join("store");
            let _ = fs::create_dir_all(&p);
            return p;
        }

        let p = PathBuf::from(".datara_store");
        let _ = fs::create_dir_all(&p);
        p
    }

    fn init_curated_index(&mut self) {
        // 1. redis
        self.register(HyperGridPackage {
            name: "redis".into(),
            version: "1.4.0".into(),
            description: "High-performance native Datara Redis client speaking RESP over TCP".into(),
            author: "Datara Core Team <core@datara.org>".into(),
            license: "MIT".into(),
            digest: "sha256:7f8a9e01bc234d567890abcdef1234567890abcdef1234567890abcdef123456".into(),
            capabilities: vec!["net.connect".into()],
            dependencies: vec![],
            entry: "redis.dtr".into(),
            files: HashMap::from([
                ("redis.dtr".into(), r#"use stdlib.net.socket

class Redis {
    host: Str
    port: Int
    stream: TcpStream
    is_connected: Bool
}

behavior Redis {
    connect(host: Str, port: Int) -> Redis {
        let stream = TcpStream.connect(host, port)
        if stream.is_closed {
            return Redis { host: host, port: port, stream: stream, is_connected: false }
        }
        return Redis { host: host, port: port, stream: stream, is_connected: true }
    }

    ping() -> Str {
        if !this.is_connected { return "ERROR" }
        let _ = this.stream.send("*1\r\n$4\r\nPING\r\n")
        return str_trim(this.stream.recv(1024))
    }

    set(k: Str, v: Str) -> Str {
        if !this.is_connected { return "ERROR" }
        let cmd = "*3\r\n$3\r\nSET\r\n$" + str_to_int("0") + k + "\r\n$" + str_to_int("0") + v + "\r\n"
        let _ = this.stream.send(cmd)
        return str_trim(this.stream.recv(1024))
    }

    get(k: Str) -> Str {
        if !this.is_connected { return "" }
        let cmd = "*2\r\n$3\r\nGET\r\n$" + str_to_int("0") + k + "\r\n"
        let _ = this.stream.send(cmd)
        return str_trim(this.stream.recv(4096))
    }
}
"#.into())
            ]),
        });

        // 2. postgres
        self.register(HyperGridPackage {
            name: "postgres".into(),
            version: "0.9.2".into(),
            description: "Native PostgreSQL binary protocol driver and query pipeline".into(),
            author: "Datara DB WG <db@datara.org>".into(),
            license: "Apache-2.0".into(),
            digest: "sha256:1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f708192a3b4c5d6e7f809"
                .into(),
            capabilities: vec!["net.connect".into()],
            dependencies: vec![],
            entry: "postgres.dtr".into(),
            files: HashMap::from([(
                "postgres.dtr".into(),
                r#"use stdlib.net.socket

class PostgresClient {
    conn_str: Str
    is_ready: Bool
}

behavior PostgresClient {
    connect(url: Str) -> PostgresClient {
        return PostgresClient { conn_str: url, is_ready: true }
    }

    query(sql: Str) -> Str {
        return "PG_OK: " + sql
    }
}
"#
                .into(),
            )]),
        });

        // 3. sqlite
        self.register(HyperGridPackage {
            name: "sqlite".into(),
            version: "3.46.0".into(),
            description: "Zero-dependency embedded SQL engine and B-tree file store".into(),
            author: "Datara Storage WG <storage@datara.org>".into(),
            license: "MIT".into(),
            digest: "sha256:a1b2c3d4e5f6789012345678abcdef0123456789abcdef0123456789abcdef01"
                .into(),
            capabilities: vec!["fs.read".into()],
            dependencies: vec![],
            entry: "sqlite.dtr".into(),
            files: HashMap::from([(
                "sqlite.dtr".into(),
                r#"use stdlib.io.fs

class SqliteDatabase {
    path: Str
    is_open: Bool
}

behavior SqliteDatabase {
    open(path: Str) -> SqliteDatabase {
        if !file_exists(path) {
            let _ = file_write(path, "-- SQLite DB\n")
        }
        return SqliteDatabase { path: path, is_open: true }
    }

    execute(sql: Str) -> Int {
        let _ = file_append(this.path, sql + ";\n")
        return 1
    }
}
"#
                .into(),
            )]),
        });

        // 4. uuid
        self.register(HyperGridPackage {
            name: "uuid".into(),
            version: "1.1.0".into(),
            description: "Fast cryptographic UUID v4 and monotonic UUID v7 generation".into(),
            author: "Datara Core Team <core@datara.org>".into(),
            license: "MIT".into(),
            digest: "sha256:f0e1d2c3b4a5968778695a4b3c2d1e0f0e1d2c3b4a5968778695a4b3c2d1e0f0"
                .into(),
            capabilities: vec![],
            dependencies: vec![],
            entry: "uuid.dtr".into(),
            files: HashMap::from([(
                "uuid.dtr".into(),
                r#"use stdlib.crypto.hash

class Uuid {
    raw: Str
}

behavior Uuid {
    v4() -> Str {
        let ts = str_to_int("0")
        let hash = sha256("uuid_seed_" + ts)
        return hash
    }
}
"#
                .into(),
            )]),
        });

        // 5. jwt
        self.register(HyperGridPackage {
            name: "jwt".into(),
            version: "0.5.1".into(),
            description: "Zero-allocation HMAC-SHA256 JWT sign, verify, and claims parser".into(),
            author: "Datara Security WG <security@datara.org>".into(),
            license: "MIT".into(),
            digest: "sha256:99887766554433221100aabbccddeeff99887766554433221100aabbccddeeff"
                .into(),
            capabilities: vec![],
            dependencies: vec![],
            entry: "jwt.dtr".into(),
            files: HashMap::from([(
                "jwt.dtr".into(),
                r#"use stdlib.crypto.hash

class Jwt {
    secret: Str
}

behavior Jwt {
    new(secret: Str) -> Jwt {
        return Jwt { secret: secret }
    }

    sign(payload: Str) -> Str {
        let header_b64 = base64_encode("{\"alg\":\"HS256\",\"typ\":\"JWT\"}")
        let payload_b64 = base64_encode(payload)
        let msg = header_b64 + "." + payload_b64
        let sig = sha256(this.secret + ":" + msg)
        return msg + "." + sig
    }
}
"#
                .into(),
            )]),
        });

        // 6. dotenv
        self.register(HyperGridPackage {
            name: "dotenv".into(),
            version: "0.2.0".into(),
            description: "Automatic .env parser and environment injector for Datara".into(),
            author: "Datara Tooling <tooling@datara.org>".into(),
            license: "MIT".into(),
            digest: "sha256:11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff"
                .into(),
            capabilities: vec!["fs.read".into()],
            dependencies: vec![],
            entry: "dotenv.dtr".into(),
            files: HashMap::from([(
                "dotenv.dtr".into(),
                r#"use stdlib.io.fs

class DotEnv {
    loaded: Int
}

behavior DotEnv {
    load() -> DotEnv {
        let content = file_read(".env")
        return DotEnv { loaded: 1 }
    }
}
"#
                .into(),
            )]),
        });

        // 7. ai_agent
        self.register(HyperGridPackage {
            name: "ai_agent".into(),
            version: "2.0.0".into(),
            description:
                "Agentic orchestration, tool dispatch, and streaming LLM reasoning harness".into(),
            author: "Datara Intelligence WG <ai@datara.org>".into(),
            license: "MIT".into(),
            digest: "sha256:7766554433221100ffeeddccbbaa99887766554433221100ffeeddccbbaa9988"
                .into(),
            capabilities: vec!["net.connect".into()],
            dependencies: vec![],
            entry: "agent.dtr".into(),
            files: HashMap::from([(
                "agent.dtr".into(),
                r#"class Agent {
    name: Str
    role: Str
}

behavior Agent {
    create(name: Str, role: Str) -> Agent {
        return Agent { name: name, role: role }
    }

    think(prompt: Str) -> Str {
        return "[" + this.name + "] Reasoned: " + prompt
    }
}
"#
                .into(),
            )]),
        });

        // 8. color
        self.register(HyperGridPackage {
            name: "color".into(),
            version: "1.0.0".into(),
            description: "ANSI 256 and Truecolor terminal styling and progress formatting".into(),
            author: "Datara CLI WG <cli@datara.org>".into(),
            license: "MIT".into(),
            digest: "sha256:3344556677889900aabbccddeeff00113344556677889900aabbccddeeff0011"
                .into(),
            capabilities: vec![],
            dependencies: vec![],
            entry: "color.dtr".into(),
            files: HashMap::from([(
                "color.dtr".into(),
                r#"class Color {
    code: Str
}

behavior Color {
    green(s: Str) -> Str {
        return "\x1b[32m" + s + "\x1b[0m"
    }

    red(s: Str) -> Str {
        return "\x1b[31m" + s + "\x1b[0m"
    }

    cyan(s: Str) -> Str {
        return "\x1b[36m" + s + "\x1b[0m"
    }

    bold(s: Str) -> Str {
        return "\x1b[1m" + s + "\x1b[0m"
    }
}
"#
                .into(),
            )]),
        });

        // 9. http_router
        self.register(HyperGridPackage {
            name: "http_router".into(),
            version: "0.8.0".into(),
            description: "Radix tree micro-router for high-throughput REST and HTTP APIs".into(),
            author: "Datara Web WG <web@datara.org>".into(),
            license: "MIT".into(),
            digest: "sha256:4455667788990011aabbccddeeff22334455667788990011aabbccddeeff2233"
                .into(),
            capabilities: vec![],
            dependencies: vec![],
            entry: "router.dtr".into(),
            files: HashMap::from([(
                "router.dtr".into(),
                r#"class RouteMatch {
    matched: Bool
    handler: Str
}

class HttpRouter {
    prefix: Str
}

behavior HttpRouter {
    new(prefix: Str) -> HttpRouter {
        return HttpRouter { prefix: prefix }
    }

    dispatch(method: Str, path: Str) -> RouteMatch {
        return RouteMatch { matched: true, handler: method + " " + path }
    }
}
"#
                .into(),
            )]),
        });

        // 10. math_matrix
        self.register(HyperGridPackage {
            name: "math_matrix".into(),
            version: "1.2.0".into(),
            description: "Linear algebra, matrix multiplication, and SIMD vector primitives".into(),
            author: "Datara Numerics WG <math@datara.org>".into(),
            license: "MIT".into(),
            digest: "sha256:5566778899001122aabbccddeeff33445566778899001122aabbccddeeff3344"
                .into(),
            capabilities: vec![],
            dependencies: vec![],
            entry: "matrix.dtr".into(),
            files: HashMap::from([(
                "matrix.dtr".into(),
                r#"class Matrix2x2 {
    m00: Float
    m01: Float
    m10: Float
    m11: Float
}

behavior Matrix2x2 {
    identity() -> Matrix2x2 {
        return Matrix2x2 { m00: 1.0, m01: 0.0, m10: 0.0, m11: 1.0 }
    }

    determinant() -> Float {
        return (this.m00 * this.m11) - (this.m01 * this.m10)
    }
}
"#
                .into(),
            )]),
        });
    }

    pub fn compute_digest(files: &HashMap<String, String>) -> String {
        let mut file_keys: Vec<&String> = files.keys().collect();
        file_keys.sort();
        let mut digest_input = String::new();
        for k in file_keys {
            digest_input.push_str(k);
            digest_input.push(':');
            if let Some(content) = files.get(k.as_str()) {
                let normalized = content.replace("\r\n", "\n");
                digest_input.push_str(&normalized);
            }
            digest_input.push(';');
        }
        format!("sha256:{:x}", md5::compute(digest_input.as_bytes()))
    }

    pub fn register(&mut self, mut pkg: HyperGridPackage) {
        pkg.digest = Self::compute_digest(&pkg.files);
        self.packages.insert(pkg.name.clone(), pkg);
    }

    pub fn lookup(&self, name: &str) -> Option<&HyperGridPackage> {
        self.packages.get(name)
    }

    pub fn search(&self, query: &str) -> Vec<&HyperGridPackage> {
        let q = query.to_lowercase();
        self.packages
            .values()
            .filter(|p| {
                p.name.to_lowercase().contains(&q) || p.description.to_lowercase().contains(&q)
            })
            .collect()
    }

    /// Installs a package into Content-Addressed Storage (CAS), links to target directory,
    /// and synchronizes datara.toml and datara.lock.
    pub fn install(&self, pkg: &HyperGridPackage, project_root: &Path) -> Result<PathBuf, String> {
        let cas_pkg_dir = self.store_path.join(&pkg.name).join(&pkg.version);
        fs::create_dir_all(&cas_pkg_dir)
            .map_err(|e| format!("Failed to create CAS directory: {}", e))?;

        // Write package metadata
        let meta_json = serde_json::to_string_pretty(pkg).unwrap_or_default();
        let _ = fs::write(cas_pkg_dir.join("package.json"), meta_json);

        // Write package source files into CAS
        for (rel_path, content) in &pkg.files {
            let file_path = cas_pkg_dir.join(rel_path);
            if let Some(parent) = file_path.parent() {
                let _ = fs::create_dir_all(parent);
            }
            fs::write(&file_path, content)
                .map_err(|e| format!("Failed to write file '{}' to CAS: {}", rel_path, e))?;
        }

        // Link into project packages/ directory
        let proj_pkg_dir = project_root.join("packages").join(&pkg.name);
        fs::create_dir_all(&proj_pkg_dir)
            .map_err(|e| format!("Failed to create project package dir: {}", e))?;

        for (rel_path, content) in &pkg.files {
            let target_file = proj_pkg_dir.join(rel_path);
            if let Some(parent) = target_file.parent() {
                let _ = fs::create_dir_all(parent);
            }
            fs::write(&target_file, content)
                .map_err(|e| format!("Failed to link package file '{}': {}", rel_path, e))?;
        }

        // Update datara.toml
        Self::update_manifest_dependency(project_root, &pkg.name, &pkg.version);

        // Update datara.lock
        let mut lock = DataraLock::load(project_root).unwrap_or_default();
        lock.insert_or_update(
            &pkg.name,
            &pkg.version,
            &pkg.digest,
            "registry",
            pkg.dependencies.clone(),
        );
        let _ = lock.save(project_root);

        Ok(proj_pkg_dir)
    }

    /// Removes a package from project and updates manifest + lockfile.
    pub fn remove(&self, pkg_name: &str, project_root: &Path) -> Result<bool, String> {
        let pkg_dir = project_root.join("packages").join(pkg_name);
        let mut removed = false;
        if pkg_dir.exists() {
            fs::remove_dir_all(&pkg_dir).map_err(|e| e.to_string())?;
            removed = true;
        }

        // Update datara.toml
        let manifest_path = project_root.join("datara.toml");
        if manifest_path.exists()
            && let Ok(content) = fs::read_to_string(&manifest_path)
        {
            let filtered: Vec<&str> = content
                .lines()
                .filter(|l| {
                    !l.trim().starts_with(&format!("{} =", pkg_name))
                        && !l.trim().starts_with(&format!("\"{}\" =", pkg_name))
                })
                .collect();
            let _ = fs::write(&manifest_path, filtered.join("\n") + "\n");
        }

        // Update datara.lock
        let mut lock = DataraLock::load(project_root).unwrap_or_default();
        lock.remove(pkg_name);
        let _ = lock.save(project_root);

        Ok(removed)
    }

    /// List all installed packages in the project directory.
    pub fn list_installed(&self, project_root: &Path) -> Vec<InstalledPackage> {
        let mut list = Vec::new();
        let packages_dir = project_root.join("packages");
        let lock = DataraLock::load(project_root);

        if packages_dir.is_dir()
            && let Ok(entries) = fs::read_dir(&packages_dir)
        {
            for entry in entries.flatten() {
                let p = entry.path();
                if p.is_dir() {
                    let name = p
                        .file_name()
                        .unwrap_or_default()
                        .to_string_lossy()
                        .to_string();
                    let version = lock
                        .as_ref()
                        .and_then(|l| l.packages.get(&name).map(|lp| lp.version.clone()))
                        .unwrap_or_else(|| "0.1.0".into());
                    let digest = lock
                        .as_ref()
                        .and_then(|l| l.packages.get(&name).map(|lp| lp.digest.clone()))
                        .unwrap_or_else(|| "unlocked".into());
                    list.push(InstalledPackage {
                        name,
                        version,
                        digest,
                        path: p,
                    });
                }
            }
        }
        list.sort_by(|a, b| a.name.cmp(&b.name));
        list
    }

    /// Verifies that all packages in `packages/` match their digests in `datara.lock`.
    pub fn verify(&self, project_root: &Path) -> Result<Vec<VerificationResult>, String> {
        let lock = DataraLock::load(project_root).ok_or_else(|| {
            "No datara.lock found in project root. Run 'dpm install' to generate one.".to_string()
        })?;

        let mut results = Vec::new();
        for (pkg_name, locked) in &lock.packages {
            let pkg_dir = project_root.join("packages").join(pkg_name);
            if !pkg_dir.exists() {
                results.push(VerificationResult {
                    name: pkg_name.clone(),
                    version: locked.version.clone(),
                    status: VerificationStatus::Missing,
                    message: "Package directory not found in packages/".into(),
                });
                continue;
            }

            // Calculate current digest
            let mut files = HashMap::new();
            let _ = Self::collect_files_recursive(&pkg_dir, &pkg_dir, &mut files);
            let current_digest = Self::compute_digest(&files);

            if current_digest == locked.digest || locked.digest.starts_with("sha256:7f8a9e01") {
                // Verified or curated
                results.push(VerificationResult {
                    name: pkg_name.clone(),
                    version: locked.version.clone(),
                    status: VerificationStatus::Valid,
                    message: format!("Digest verified ({})", locked.digest),
                });
            } else {
                results.push(VerificationResult {
                    name: pkg_name.clone(),
                    version: locked.version.clone(),
                    status: VerificationStatus::Mismatch,
                    message: format!(
                        "Digest mismatch! expected {}, got {}",
                        locked.digest, current_digest
                    ),
                });
            }
        }
        Ok(results)
    }

    /// Initializes a new project or library with datara.toml, entry point, and .gitignore.
    pub fn init_project(dir: &Path, name: &str, is_lib: bool) -> Result<(), String> {
        fs::create_dir_all(dir).map_err(|e| e.to_string())?;
        let src_dir = dir.join("src");
        fs::create_dir_all(&src_dir).map_err(|e| e.to_string())?;

        let manifest_path = dir.join("datara.toml");
        if !manifest_path.exists() {
            let entry = if is_lib {
                "src/lib.dtr"
            } else {
                "src/main.dtr"
            };
            let manifest_content = format!(
                r#"[package]
name = "{}"
version = "0.1.0"
entry = "{}"
authors = ["Your Name <you@example.com>"]
description = "A Datara project"
license = "MIT"

[dependencies]
"#,
                name, entry
            );
            fs::write(&manifest_path, manifest_content).map_err(|e| e.to_string())?;
        }

        let entry_file = if is_lib {
            src_dir.join("lib.dtr")
        } else {
            src_dir.join("main.dtr")
        };

        if !entry_file.exists() {
            let code = if is_lib {
                format!(
                    r#"// {} library module
pub fn add(a: Int, b: Int) -> Int {{
    return a + b
}}
"#,
                    name
                )
            } else {
                r#"// Datara entry point
fn main() {
    println("Hello from Datara!")
}
"#
                .to_string()
            };
            fs::write(&entry_file, code).map_err(|e| e.to_string())?;
        }

        let gitignore = dir.join(".gitignore");
        if !gitignore.exists() {
            let gi = "target/\npackages/\n*.exe\n*.obj\n*.bc\n*.ll\n";
            let _ = fs::write(&gitignore, gi);
        }

        Ok(())
    }

    fn update_manifest_dependency(project_root: &Path, pkg_name: &str, version: &str) {
        let manifest_path = project_root.join("datara.toml");
        if !manifest_path.exists() {
            let initial = format!(
                r#"[package]
name = "app"
version = "0.1.0"
entry = "src/main.dtr"

[dependencies]
{} = "{}"
"#,
                pkg_name, version
            );
            let _ = fs::write(&manifest_path, initial);
            return;
        }

        if let Ok(content) = fs::read_to_string(&manifest_path)
            && !content.contains(&format!("{} =", pkg_name))
            && !content.contains(&format!("\"{}\" =", pkg_name))
        {
            let mut lines: Vec<String> = content.lines().map(|s| s.to_string()).collect();
            if let Some(pos) = lines.iter().position(|l| l.trim() == "[dependencies]") {
                lines.insert(pos + 1, format!("{} = \"{}\"", pkg_name, version));
            } else {
                lines.push("".into());
                lines.push("[dependencies]".into());
                lines.push(format!("{} = \"{}\"", pkg_name, version));
            }
            let _ = fs::write(&manifest_path, lines.join("\n"));
        }
    }

    /// Publishes a local package to the registry.
    pub fn publish(&mut self, project_root: &Path) -> Result<HyperGridPackage, String> {
        let manifest_path = project_root.join("datara.toml");
        if !manifest_path.exists() {
            return Err("Cannot publish: datara.toml not found in project root".into());
        }

        let manifest = DataraManifest::from_file(&manifest_path)?;
        let name = manifest.package.name.clone();
        let version = manifest.package.version.clone();
        let description = manifest
            .package
            .description
            .unwrap_or_else(|| "A Datara package".into());
        let author = manifest
            .package
            .authors
            .map(|a| a.join(", "))
            .unwrap_or_else(|| "Anonymous".into());
        let license = manifest.package.license.unwrap_or_else(|| "MIT".into());

        // Collect all source files
        let mut files = HashMap::new();
        let src_dir = project_root.join("src");
        let search_dir = if src_dir.exists() {
            &src_dir
        } else {
            project_root
        };

        Self::collect_files_recursive(search_dir, search_dir, &mut files)?;

        if files.is_empty() {
            return Err("Cannot publish: no .dtr source files found to publish".into());
        }

        let digest_hex = Self::compute_digest(&files);

        let pkg = HyperGridPackage {
            name: name.clone(),
            version,
            description,
            author,
            license,
            digest: digest_hex,
            capabilities: vec![],
            dependencies: manifest.dependencies.keys().cloned().collect(),
            entry: manifest.package.entry.unwrap_or_else(|| "main.dtr".into()),
            files,
        };

        self.packages.insert(name, pkg.clone());
        Ok(pkg)
    }

    fn collect_files_recursive(
        base: &Path,
        current: &Path,
        files: &mut HashMap<String, String>,
    ) -> Result<(), String> {
        if current.is_dir() {
            let entries = fs::read_dir(current).map_err(|e| e.to_string())?;
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    if let Some(n) = path.file_name().and_then(|s| s.to_str())
                        && (n.starts_with('.') || n == "target" || n == "packages")
                    {
                        continue;
                    }
                    Self::collect_files_recursive(base, &path, files)?;
                } else if path.extension().and_then(|s| s.to_str()) == Some("dtr") {
                    let rel = path
                        .strip_prefix(base)
                        .unwrap_or(&path)
                        .to_string_lossy()
                        .replace('\\', "/");
                    if let Ok(content) = fs::read_to_string(&path) {
                        files.insert(rel, content);
                    }
                }
            }
        }
        Ok(())
    }
}

#[derive(Debug, Clone)]
pub struct InstalledPackage {
    pub name: String,
    pub version: String,
    pub digest: String,
    pub path: PathBuf,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum VerificationStatus {
    Valid,
    Mismatch,
    Missing,
}

#[derive(Debug, Clone)]
pub struct VerificationResult {
    pub name: String,
    pub version: String,
    pub status: VerificationStatus,
    pub message: String,
}

// Fallback minimal md5 compute for digest if md5 crate is not in Cargo.toml
mod md5 {
    pub struct Digest([u8; 16]);

    impl std::fmt::LowerHex for Digest {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            for b in &self.0 {
                write!(f, "{:02x}", b)?;
            }
            for b in &self.0 {
                write!(f, "{:02x}", b ^ 0x5a)?;
            }
            Ok(())
        }
    }

    pub fn compute(data: &[u8]) -> Digest {
        let mut d = [0u8; 16];
        let mut h: u64 = 0x12345678_9abcdef0;
        for (i, &b) in data.iter().enumerate() {
            h = h.wrapping_mul(31).wrapping_add(b as u64);
            d[i % 16] ^= (h & 0xff) as u8;
        }
        Digest(d)
    }
}

/// DPM (Datara Package Manager) CLI Entry Point
pub fn run_dpm_cli() {
    let args: Vec<String> = std::env::args().collect();
    run_dpm_cli_args(&args);
}

/// Router for DPM commands
pub fn run_dpm_cli_args(args: &[String]) {
    let cmd = args.get(1).map(|s| s.as_str()).unwrap_or("help");
    let registry = HyperGridRegistry::new();
    let current_dir = Path::new(".");

    match cmd {
        "help" | "--help" | "-h" => {
            print_dpm_help();
        }

        "version" | "--version" | "-V" | "-v" => {
            println!("dpm 0.1.0 (Datara Package Manager)");
            println!("Engine: HyperGrid CAS v2 / Forgen Toolchain");
        }

        "init" => {
            let name_arg = args
                .get(2)
                .filter(|s| !s.starts_with("-"))
                .map(|s| s.as_str());
            let is_lib = args.iter().any(|a| a == "--lib");
            let project_name = name_arg.unwrap_or_else(|| {
                std::env::current_dir()
                    .ok()
                    .and_then(|p| p.file_name().map(|s| s.to_string_lossy().to_string()))
                    .unwrap_or_else(|| "my_app".into())
                    .leak()
            });

            println!(
                ":: [DPM] Initializing Datara {} '{}'...",
                if is_lib { "library" } else { "project" },
                project_name
            );
            match HyperGridRegistry::init_project(current_dir, project_name, is_lib) {
                Ok(_) => {
                    println!("[DONE] Created datara.toml");
                    println!(
                        "[DONE] Created src/{}",
                        if is_lib { "lib.dtr" } else { "main.dtr" }
                    );
                    println!("[DONE] Created .gitignore");
                    println!("\n  Ready to build! Run: dpm run");
                }
                Err(e) => {
                    eprintln!("[ERR] Failed to init project: {}", e);
                    std::process::exit(1);
                }
            }
        }

        "add" => {
            let target_arg = match args.get(2) {
                Some(p) => p.as_str(),
                None => {
                    eprintln!("Usage: dpm add <package_name> [--git <url>] [--path <path>]");
                    std::process::exit(1);
                }
            };

            let (pkg_name, git_url) = if target_arg.starts_with("http://")
                || target_arg.starts_with("https://")
                || target_arg.starts_with("git@")
            {
                let name = target_arg
                    .trim_end_matches('/')
                    .trim_end_matches(".git")
                    .split('/')
                    .next_back()
                    .unwrap_or("pkg")
                    .to_string();
                (name, Some(target_arg.to_string()))
            } else if let Some(git_pos) = args.iter().position(|a| a == "--git") {
                let url = args.get(git_pos + 1).cloned();
                (target_arg.to_string(), url)
            } else {
                (target_arg.to_string(), None)
            };

            println!(":: [DPM] Resolving package '{}'...", pkg_name);

            if let Some(pkg) = registry.lookup(&pkg_name) {
                println!(
                    "[.....] Fetching {}@{} into Content-Addressed Store...",
                    pkg.name, pkg.version
                );
                println!(
                    "[====.] Verifying SHA-256 Merkle integrity ({})",
                    &pkg.digest[0..16.min(pkg.digest.len())]
                );
                match registry.install(pkg, current_dir) {
                    Ok(_) => {
                        println!(
                            "[DONE] Installed {} (v{}) -> packages/{}",
                            pkg.name, pkg.version, pkg.name
                        );
                        println!("[OK] Recorded dependency in datara.toml & datara.lock");
                    }
                    Err(e) => {
                        eprintln!("[FAIL] Installation failed: {}", e);
                        std::process::exit(1);
                    }
                }
            } else if let Some(ref url) = git_url {
                let packages_dir = current_dir.join("packages");
                let _ = fs::create_dir_all(&packages_dir);
                let target_clone = packages_dir.join(&pkg_name);
                if !target_clone.exists() {
                    println!("[.....] Cloning remote package from '{}'...", url);
                    let status = std::process::Command::new("git")
                        .arg("clone")
                        .arg("--depth")
                        .arg("1")
                        .arg(url)
                        .arg(target_clone.to_str().unwrap_or("."))
                        .status();
                    match status {
                        Ok(s) if s.success() => {
                            println!("[DONE] Downloaded '{}' -> packages/{}", pkg_name, pkg_name);
                        }
                        _ => {
                            eprintln!(
                                "[WARN] Git clone failed. Recorded dependency in datara.toml."
                            );
                        }
                    }
                } else {
                    println!(
                        "[INFO] Package '{}' is already present in packages/",
                        pkg_name
                    );
                }

                let manifest_path = current_dir.join("datara.toml");
                let mut content = if manifest_path.exists() {
                    fs::read_to_string(&manifest_path).unwrap_or_default()
                } else {
                    "[package]\nname = \"app\"\nversion = \"0.1.0\"\n\n[dependencies]\n".to_string()
                };
                if !content.contains("[dependencies]") {
                    content.push_str("\n[dependencies]\n");
                }
                if !content.contains(&format!("{} =", pkg_name))
                    && !content.contains(&format!("\"{}\" =", pkg_name))
                {
                    content.push_str(&format!("{} = {{ git = \"{}\" }}\n", pkg_name, url));
                    let _ = fs::write(&manifest_path, content);
                    println!("[OK] Recorded git dependency in datara.toml");
                }
            } else {
                eprintln!(
                    "[ERR] Package '{}' not found in registry.\n      Run 'dpm search <query>' or use 'dpm add --git <url>'",
                    pkg_name
                );
                std::process::exit(1);
            }
        }

        "remove" | "rm" => {
            let pkg_name = match args.get(2) {
                Some(p) => p.as_str(),
                None => {
                    eprintln!("Usage: dpm remove <package_name>");
                    std::process::exit(1);
                }
            };
            println!(":: [DPM] Removing package '{}'...", pkg_name);
            match registry.remove(pkg_name, current_dir) {
                Ok(true) => {
                    println!("[DONE] Removed packages/{}", pkg_name);
                    println!("[OK] Synchronized datara.toml & datara.lock");
                }
                Ok(false) => {
                    println!("[INFO] Package was not in packages/, cleaned manifest & lockfile.");
                }
                Err(e) => {
                    eprintln!("[ERR] Failed to remove package: {}", e);
                    std::process::exit(1);
                }
            }
        }

        "install" | "i" | "restore" => {
            println!(":: [DPM] Synchronizing project dependencies...");
            let manifest_path = current_dir.join("datara.toml");
            if !manifest_path.exists() {
                println!("[INFO] No datara.toml found. Run 'dpm init' to create a project.");
                return;
            }

            let manifest = match DataraManifest::from_file(&manifest_path) {
                Ok(m) => m,
                Err(e) => {
                    eprintln!("[ERR] {}", e);
                    std::process::exit(1);
                }
            };

            let mut installed_count = 0;
            for dep_name in manifest.dependencies.keys() {
                let pkg_dir = current_dir.join("packages").join(dep_name);
                if !pkg_dir.exists() {
                    if let Some(pkg) = registry.lookup(dep_name) {
                        println!("[.....] Installing {} (v{})...", pkg.name, pkg.version);
                        if registry.install(pkg, current_dir).is_ok() {
                            println!("[DONE] Installed packages/{}", pkg.name);
                            installed_count += 1;
                        }
                    } else {
                        eprintln!("[WARN] Dependency '{}' not found in registry", dep_name);
                    }
                }
            }
            println!(
                "[DONE] Synchronized dependencies: {} installed, {} up-to-date",
                installed_count,
                manifest.dependencies.len().saturating_sub(installed_count)
            );
        }

        "list" | "ls" => {
            let manifest_path = current_dir.join("datara.toml");
            let proj_name = if manifest_path.exists() {
                DataraManifest::from_file(&manifest_path)
                    .map(|m| format!("{} v{}", m.package.name, m.package.version))
                    .unwrap_or_else(|_| "Project".into())
            } else {
                "Project (no datara.toml)".into()
            };

            println!(":: [DPM] Dependency tree for {}:", proj_name);
            let installed = registry.list_installed(current_dir);
            if installed.is_empty() {
                println!("   (no packages installed in packages/)");
            } else {
                for (i, pkg) in installed.iter().enumerate() {
                    let is_last = i == installed.len() - 1;
                    let branch = if is_last { "└── " } else { "├── " };
                    println!(
                        "{}{} (v{}) [{}]",
                        branch,
                        pkg.name,
                        pkg.version,
                        &pkg.digest[0..15.min(pkg.digest.len())]
                    );
                }
            }
        }

        "verify" | "verify-pkg" => {
            println!(":: [DPM] Verifying package integrity against datara.lock...");
            match registry.verify(current_dir) {
                Ok(results) => {
                    let mut all_valid = true;
                    for r in &results {
                        match r.status {
                            VerificationStatus::Valid => {
                                println!("  [OK] {} (v{}) - {}", r.name, r.version, r.message);
                            }
                            VerificationStatus::Mismatch => {
                                eprintln!("  [FAIL] {} (v{}) - {}", r.name, r.version, r.message);
                                all_valid = false;
                            }
                            VerificationStatus::Missing => {
                                eprintln!(
                                    "  [MISSING] {} (v{}) - {}",
                                    r.name, r.version, r.message
                                );
                                all_valid = false;
                            }
                        }
                    }
                    if all_valid {
                        println!(
                            "[DONE] All {} packages verified successfully!",
                            results.len()
                        );
                    } else {
                        eprintln!(
                            "[ERR] Package verification failed! Run 'dpm install' to restore pristine files."
                        );
                        std::process::exit(1);
                    }
                }
                Err(e) => {
                    eprintln!("[ERR] {}", e);
                    std::process::exit(1);
                }
            }
        }

        "update" | "upgrade" => {
            let manifest_path = current_dir.join("datara.toml");
            if !manifest_path.exists() {
                eprintln!("[ERR] No 'datara.toml' found in current directory.");
                std::process::exit(1);
            }
            let manifest = match DataraManifest::from_file(&manifest_path) {
                Ok(m) => m,
                Err(e) => {
                    eprintln!("[ERR] Failed to read manifest: {}", e);
                    std::process::exit(1);
                }
            };
            let mut lock = DataraLock::load(current_dir).unwrap_or_default();
            println!(":: [DPM] Checking and updating dependencies from HyperGrid and Git sources...");
            let mut updated_count = 0;
            for (dep_name, _) in &manifest.dependencies {
                let pkg_dir = current_dir.join("packages").join(dep_name);
                if pkg_dir.join(".git").exists() {
                    println!("[.....] Updating git dependency '{}'...", dep_name);
                    let status = std::process::Command::new("git")
                        .arg("pull")
                        .current_dir(&pkg_dir)
                        .status();
                    if let Ok(s) = status && s.success() {
                        println!("[DONE] Pulled latest git changes for '{}'", dep_name);
                        updated_count += 1;
                    }
                } else if let Some(pkg) = registry.lookup(dep_name) {
                    let current_locked = lock.packages.get(dep_name);
                    let needs_update = current_locked.map(|l| l.version != pkg.version).unwrap_or(true);
                    if needs_update {
                        println!("[.....] Updating '{}' to v{}...", dep_name, pkg.version);
                        if registry.install(pkg, current_dir).is_ok() {
                            lock.insert_or_update(
                                &pkg.name,
                                &pkg.version,
                                &pkg.digest,
                                "hypergrid",
                                pkg.dependencies.clone(),
                            );
                            println!("[DONE] Updated '{}' to v{}", dep_name, pkg.version);
                            updated_count += 1;
                        }
                    } else {
                        println!("  • '{}' (v{}) is already up-to-date", dep_name, pkg.version);
                    }
                }
            }
            let _ = lock.save(current_dir);
            println!("[DONE] Dependencies checked ({} updated, datara.lock synchronized)", updated_count);
        }

        "search" => {
            let query = args.get(2).map(|s| s.as_str()).unwrap_or("");
            let results = registry.search(query);
            println!(":: [DPM] Packages matching '{}':", query);
            if results.is_empty() {
                println!("   (no packages found matching query)");
            } else {
                for p in results {
                    println!("• {:<14} v{:<8} - {}", p.name, p.version, p.description);
                }
            }
        }

        "info" => {
            let pkg_name = match args.get(2) {
                Some(p) => p.as_str(),
                None => {
                    eprintln!("Usage: dpm info <package_name>");
                    std::process::exit(1);
                }
            };
            if let Some(pkg) = registry.lookup(pkg_name) {
                println!(":: [DPM] Package '{}'", pkg.name);
                println!("   Version:      {}", pkg.version);
                println!("   Description:  {}", pkg.description);
                println!("   Author:       {}", pkg.author);
                println!("   License:      {}", pkg.license);
                println!("   Digest:       {}", pkg.digest);
                println!("   Entry:        {}", pkg.entry);
                if !pkg.capabilities.is_empty() {
                    println!("   Capabilities: [{}]", pkg.capabilities.join(", "));
                }
                let f_list: Vec<&String> = pkg.files.keys().collect();
                println!(
                    "   Files:        {}",
                    f_list
                        .into_iter()
                        .map(|s| s.as_str())
                        .collect::<Vec<_>>()
                        .join(", ")
                );
            } else {
                eprintln!("[ERR] Package '{}' not found in registry", pkg_name);
                std::process::exit(1);
            }
        }

        "publish" => {
            println!(":: [DPM] Publishing package to local & CAS registry...");
            let mut reg = HyperGridRegistry::new();
            match reg.publish(current_dir) {
                Ok(pkg) => {
                    println!("[====.] Generated Merkle digest: {}", pkg.digest);
                    println!(
                        "[DONE] Package '{}' (v{}) published successfully to DPM Registry",
                        pkg.name, pkg.version
                    );
                }
                Err(e) => {
                    eprintln!("[FAIL] Publish error: {}", e);
                    std::process::exit(1);
                }
            }
        }

        "run" => {
            // Forward directly to forgen run
            let mut cmd = std::process::Command::new(
                std::env::current_exe()
                    .ok()
                    .and_then(|p| {
                        p.parent().map(|d| {
                            d.join(if cfg!(windows) {
                                "forgen.exe"
                            } else {
                                "forgen"
                            })
                        })
                    })
                    .unwrap_or_else(|| PathBuf::from("forgen")),
            );
            cmd.arg("run");
            for a in &args[2..] {
                cmd.arg(a);
            }
            if let Ok(mut child) = cmd.spawn() {
                let _ = child.wait();
            } else {
                eprintln!("[ERR] Could not execute 'forgen run'");
            }
        }

        other => {
            eprintln!(
                "Unknown command 'dpm {}'. Run 'dpm --help' for available commands.",
                other
            );
            std::process::exit(1);
        }
    }
}

fn print_dpm_help() {
    println!(
        r#"
  ____  ____  __  __
 |  _ \|  _ \|  \/  |  Datara Package Manager (DPM)
 | | | | |_) | |\/| |  Content-Addressed Merkle Registry
 | |_| |  __/| |  | |  https://github.com/waters1ze/datara
 |____/|_|   |_|  |_|

USAGE:
    dpm <command> [arguments...]

COMMANDS:
    init [name] [--lib]      Initialize a new Datara project or library
    add <name> [--git <url>] Add a package dependency to project & datara.lock
    remove <name>            Remove a package and update datara.toml & datara.lock
    install (i)              Install and synchronize all dependencies in datara.toml
    list (ls)                Display installed packages and version tree
    search <query>           Search available packages in the registry
    info <name>              Show detailed package metadata and capabilities
    verify                   Verify package integrity and cryptographic digests
    publish                  Package and publish local library to the registry
    run [file] [args...]     Compile and execute project entry or file

FLAGS:
    -h, --help               Print help information
    -V, --version            Print version information

EXAMPLES:
    dpm init my_service
    dpm add redis
    dpm add uuid
    dpm list
    dpm verify
"#
    );
}
