; Script generated by Datara Core Team for Inno Setup 6+
; Compiles a standalone single-file Datara-v0.1.0-Setup.exe

#define MyAppName "Datara"
#define MyAppVersion "0.1.0"
#define MyAppPublisher "Datara Language Project"
#define MyAppURL "https://github.com/waters1ze/datara"
#define MyAppExeName "forgen.exe"

[Setup]
AppId={{D37A8A91-4F28-4B73-868C-19416D3A0A2D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\Programs\Datara
DefaultGroupName=Datara
AllowNoIcons=yes
OutputDir=..\dist
OutputBaseFilename=Datara-v{#MyAppVersion}-Setup
SetupIconFile=..\assets\datara.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ChangesEnvironment=yes
ChangesAssociations=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "envPath"; Description: "Add Datara to PATH environment variable"; GroupDescription: "System Integration:"; Flags: checkedonce
Name: "assocDtr"; Description: "Associate .dtr files with Datara and show official icon"; GroupDescription: "File Associations:"; Flags: checkedonce

[Files]
Source: "..\target\release\forgen.exe"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "..\target\release\forgen.exe"; DestDir: "{app}\bin"; DestName: "datara.exe"; Flags: ignoreversion
Source: "..\assets\datara.ico"; DestDir: "{app}\assets"; Flags: ignoreversion
Source: "..\assets\datara-logo.png"; DestDir: "{app}\assets"; Flags: ignoreversion
Source: "..\stdlib\*"; DestDir: "{app}\stdlib"; Flags: ignoreversion recursesubdirs createallsubdirs

[Registry]
; File Association
Root: HKCU; Subkey: "Software\Classes\.dtr"; ValueType: string; ValueData: "DataraSourceFile"; Flags: uninsdeletekey; Tasks: assocDtr
Root: HKCU; Subkey: "Software\Classes\.dtr"; ValueType: string; ValueName: "Content Type"; ValueData: "text/plain"; Tasks: assocDtr
Root: HKCU; Subkey: "Software\Classes\DataraSourceFile"; ValueType: string; ValueData: "Datara Source File"; Flags: uninsdeletekey; Tasks: assocDtr
Root: HKCU; Subkey: "Software\Classes\DataraSourceFile\DefaultIcon"; ValueType: string; ValueData: "{app}\assets\datara.ico,0"; Tasks: assocDtr
Root: HKCU; Subkey: "Software\Classes\DataraSourceFile\shell\open\command"; ValueType: string; ValueData: """{app}\bin\forgen.exe"" run ""%1"""; Tasks: assocDtr

; Environment Variable PATH
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{app}\bin;{olddata}"; Tasks: envPath; Check: NeedsAddPath(ExpandConstant('{app}\bin'))
Root: HKCU; Subkey: "Environment"; ValueType: string; ValueName: "DATARA_HOME"; ValueData: "{app}"; Flags: uninsdeletevalue; Tasks: envPath

[Icons]
Name: "{group}\Datara REPL"; Filename: "{app}\bin\forgen.exe"; Parameters: "repl"; IconFilename: "{app}\assets\datara.ico"
Name: "{group}\Datara Language Docs"; Filename: "{#MyAppURL}"
Name: "{group}\Uninstall Datara"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\bin\forgen.exe"; Parameters: "--version"; Description: "Verify installation in console"; Flags: nowait postinstall skipifsilent

[Code]
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
  if not RegQueryStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  Result := Pos(';' + Param + ';', ';' + OrigPath + ';') = 0;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then begin
    // Notify shell about icon and file association changes
    ChangeSysColor();
  end;
end;
